#!/usr/bin/env bash
set -euo pipefail

# sticky_bandits AP setup
# Creates a WiFi access point that routes traffic through an uplink interface

die() { echo "[FATAL] $*" >&2; exit 1; }
info() { echo "[*] $*"; }
ok() { echo "[+] $*"; }
warn() { echo "[!] $*"; }

require_root() {
  [[ "${EUID}" -eq 0 ]] || die "Run with sudo/root."
}

require_root

# --- Configuration ---
AP_IFACE="${AP_IFACE:-wlan0}"
UPLINK_IFACE="${UPLINK_IFACE:-eth0}"
SSID="${SSID:-sticky_bandits}"
PASSPHRASE="${PASSPHRASE:-change-me-now-please}"
CHANNEL="${CHANNEL:-6}"

AP_ADDR="${AP_ADDR:-192.168.60.1}"
CIDR="${CIDR:-24}"
DHCP_START="${DHCP_START:-192.168.60.10}"
DHCP_END="${DHCP_END:-192.168.60.100}"
LEASE_TIME="${LEASE_TIME:-12h}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="$REPO_ROOT/.state"
mkdir -p "$STATE_DIR" "$REPO_ROOT/logs"

info "sticky_bandits AP bring-up"
info "  AP_IFACE=$AP_IFACE"
info "  UPLINK_IFACE=$UPLINK_IFACE"
info "  SSID=$SSID"
info "  CHANNEL=$CHANNEL"
info "  AP_ADDR=$AP_ADDR/$CIDR"

# --- Validate interfaces exist ---
ip link show "$AP_IFACE" >/dev/null 2>&1 || die "AP interface $AP_IFACE not found"
ip link show "$UPLINK_IFACE" >/dev/null 2>&1 || die "Uplink interface $UPLINK_IFACE not found"

# --- Validate interfaces are different ---
[[ "$AP_IFACE" != "$UPLINK_IFACE" ]] || die "AP and uplink interfaces must be different"

# --- CLEAN SLATE: Stop everything first ---
info "Stopping all services and cleaning up..."
systemctl stop hostapd 2>/dev/null || true
systemctl stop dnsmasq 2>/dev/null || true

# Remove ALL iptables rules we created
iptables -D FORWARD -j SB_FORWARD 2>/dev/null || true
iptables -F SB_FORWARD 2>/dev/null || true
iptables -X SB_FORWARD 2>/dev/null || true
iptables -t nat -D POSTROUTING -j SB_POSTROUTING 2>/dev/null || true
iptables -t nat -F SB_POSTROUTING 2>/dev/null || true
iptables -t nat -X SB_POSTROUTING 2>/dev/null || true

# Remove config files
rm -f /etc/dnsmasq.d/sticky-bandits.conf
rm -f /etc/dnsmasq.d/intercept.conf
rm -f /etc/netplan/99-sticky-bandits.yaml

# Clear DHCP leases to avoid stale entries
rm -f /var/lib/misc/dnsmasq.leases

# --- Clean up BOTH wifi interfaces ---
info "Resetting wifi interfaces..."
for IFACE in "$AP_IFACE" "$UPLINK_IFACE"; do
  # Skip if not a wifi interface
  if ! iw dev "$IFACE" info >/dev/null 2>&1; then
    continue
  fi
  # Remove from AP mode if in it
  ip addr flush dev "$IFACE" 2>/dev/null || true
done

# --- Make sure uplink is connected and has internet ---
info "Ensuring uplink $UPLINK_IFACE is connected..."
nmcli dev set "$UPLINK_IFACE" managed yes 2>/dev/null || true

# Wait for uplink to get an IP if it doesn't have one
UPLINK_IP=$(ip addr show "$UPLINK_IFACE" 2>/dev/null | grep -oP 'inet \K[0-9.]+' | head -1 || true)
if [[ -z "$UPLINK_IP" ]]; then
  warn "Uplink $UPLINK_IFACE has no IP, waiting for DHCP..."
  sleep 5
  UPLINK_IP=$(ip addr show "$UPLINK_IFACE" 2>/dev/null | grep -oP 'inet \K[0-9.]+' | head -1 || true)
fi

if [[ -z "$UPLINK_IP" ]]; then
  die "Uplink $UPLINK_IFACE has no IP address. Connect it to a network first."
fi
info "Uplink $UPLINK_IFACE has IP: $UPLINK_IP"

# Check internet connectivity
if ! ping -c 1 -W 3 -I "$UPLINK_IFACE" 8.8.8.8 >/dev/null 2>&1; then
  warn "Uplink $UPLINK_IFACE cannot reach 8.8.8.8 - internet may not work for clients"
else
  ok "Uplink has internet connectivity"
fi

# --- Configure AP interface ---
info "Configuring AP interface $AP_IFACE..."
nmcli dev set "$AP_IFACE" managed no 2>/dev/null || true
nmcli dev disconnect "$AP_IFACE" 2>/dev/null || true

# Bring down, flush, configure, bring up
ip link set "$AP_IFACE" down 2>/dev/null || true
sleep 1
ip addr flush dev "$AP_IFACE" 2>/dev/null || true
ip addr add "$AP_ADDR/$CIDR" dev "$AP_IFACE"
ip link set "$AP_IFACE" up

# Verify
sleep 1
if ! ip addr show "$AP_IFACE" | grep -q "$AP_ADDR"; then
  ip addr show "$AP_IFACE"
  die "Failed to assign IP $AP_ADDR to $AP_IFACE"
fi
ok "$AP_IFACE configured with IP $AP_ADDR"

# --- Write hostapd config ---
HOSTAPD_CONF="/etc/hostapd/hostapd.conf"
info "Writing hostapd config..."
COUNTRY="${COUNTRY:-US}"
cat > "$HOSTAPD_CONF" <<EOF
# Generated by sticky_bandits
interface=$AP_IFACE
driver=nl80211

# Regulatory
country_code=$COUNTRY
ieee80211d=1

# Basic
ssid=$SSID
hw_mode=g
channel=$CHANNEL

# 802.11n support
ieee80211n=1
wmm_enabled=1

# Security - WPA2-PSK
auth_algs=1
wpa=2
wpa_passphrase=$PASSPHRASE
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP

# Visibility
ignore_broadcast_ssid=0
EOF

echo "DAEMON_CONF=\"$HOSTAPD_CONF\"" > /etc/default/hostapd

# --- Start hostapd ---
info "Starting hostapd..."
systemctl unmask hostapd >/dev/null 2>&1 || true
systemctl start hostapd
sleep 2

if ! systemctl is-active --quiet hostapd; then
  echo "--- hostapd failed ---"
  systemctl status hostapd --no-pager || true
  journalctl -u hostapd --no-pager -n 20 || true
  die "hostapd failed to start"
fi

if ! iw dev "$AP_IFACE" info 2>/dev/null | grep -q "type AP"; then
  iw dev "$AP_IFACE" info || true
  die "$AP_IFACE is not in AP mode"
fi
ok "hostapd running, $AP_IFACE broadcasting SSID: $SSID"

# --- Write dnsmasq config ---
info "Writing dnsmasq config..."
cat > /etc/dnsmasq.d/sticky-bandits.conf <<EOF
# Generated by sticky_bandits
interface=$AP_IFACE
bind-interfaces

# DHCP range
dhcp-range=$DHCP_START,$DHCP_END,$LEASE_TIME
dhcp-option=3,$AP_ADDR
dhcp-option=6,$AP_ADDR

# Logging
log-queries
log-dhcp
EOF

# --- Start dnsmasq ---
info "Starting dnsmasq..."
systemctl start dnsmasq
sleep 1

if ! systemctl is-active --quiet dnsmasq; then
  echo "--- dnsmasq failed ---"
  systemctl status dnsmasq --no-pager || true
  journalctl -u dnsmasq --no-pager -n 20 || true
  die "dnsmasq failed to start"
fi
ok "dnsmasq running, DHCP on $DHCP_START - $DHCP_END"

# --- Enable IP forwarding ---
info "Enabling IPv4 forwarding..."
echo 1 > /proc/sys/net/ipv4/ip_forward
echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-sticky-bandits.conf

# --- Configure iptables ---
info "Configuring iptables..."

# Forwarding chain: allow traffic between AP and uplink
iptables -N SB_FORWARD 2>/dev/null || true
iptables -F SB_FORWARD
iptables -I FORWARD 1 -j SB_FORWARD
# Traffic from uplink to AP (responses)
iptables -A SB_FORWARD -i "$UPLINK_IFACE" -o "$AP_IFACE" -m state --state RELATED,ESTABLISHED -j ACCEPT
# Traffic from AP to uplink (requests)
iptables -A SB_FORWARD -i "$AP_IFACE" -o "$UPLINK_IFACE" -j ACCEPT
iptables -A SB_FORWARD -j RETURN

# NAT chain: masquerade outbound traffic
iptables -t nat -N SB_POSTROUTING 2>/dev/null || true
iptables -t nat -F SB_POSTROUTING
iptables -t nat -I POSTROUTING 1 -j SB_POSTROUTING
iptables -t nat -A SB_POSTROUTING -o "$UPLINK_IFACE" -j MASQUERADE
iptables -t nat -A SB_POSTROUTING -j RETURN

ok "iptables configured"

# --- Save state ---
cat > "$STATE_DIR/ap_config" <<EOF
AP_IFACE=$AP_IFACE
UPLINK_IFACE=$UPLINK_IFACE
SSID=$SSID
AP_ADDR=$AP_ADDR
DHCP_START=$DHCP_START
DHCP_END=$DHCP_END
UPLINK_IP=$UPLINK_IP
EOF

# --- Final output ---
echo ""
echo "========================================"
ok "AP is ready!"
echo "========================================"
echo ""
echo "  Network: $SSID"
echo "  Password: $PASSPHRASE"
echo "  Gateway: $AP_ADDR"
echo "  DHCP: $DHCP_START - $DHCP_END"
echo ""
echo "  AP interface: $AP_IFACE"
echo "  Uplink interface: $UPLINK_IFACE ($UPLINK_IP)"
echo ""
echo "Connect a device to '$SSID' and verify it gets internet."
echo ""
echo "Then start capture:"
echo "  sudo AP_IFACE=$AP_IFACE bash scripts/capture.sh start"
echo ""
