#!/usr/bin/env bash
set -euo pipefail

# sticky_bandits AP setup
# Creates a WiFi access point that routes traffic through an uplink interface

die() { echo "[FATAL] $*" >&2; exit 1; }
info() { echo "[*] $*"; }
ok() { echo "[+] $*"; }
warn() { echo "[!] $*"; }

require_root() {
  [[ "${EUID}" -eq 0 ]] || die "Run with sudo/root."
}

have_cmd() { command -v "$1" >/dev/null 2>&1; }

require_root

# --- Configuration ---
AP_IFACE="${AP_IFACE:-wlan0}"
UPLINK_IFACE="${UPLINK_IFACE:-eth0}"
SSID="${SSID:-sticky_bandits}"
PASSPHRASE="${PASSPHRASE:-change-me-now-please}"
CHANNEL="${CHANNEL:-6}"

AP_ADDR="${AP_ADDR:-192.168.60.1}"
CIDR="${CIDR:-24}"
DHCP_START="${DHCP_START:-192.168.60.10}"
DHCP_END="${DHCP_END:-192.168.60.100}"
LEASE_TIME="${LEASE_TIME:-12h}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="$REPO_ROOT/.state"
mkdir -p "$STATE_DIR"

info "sticky_bandits AP bring-up"
info "  AP_IFACE=$AP_IFACE"
info "  UPLINK_IFACE=$UPLINK_IFACE"
info "  SSID=$SSID"
info "  CHANNEL=$CHANNEL"
info "  AP_ADDR=$AP_ADDR/$CIDR"

# --- Validate interfaces exist ---
ip link show "$AP_IFACE" >/dev/null 2>&1 || die "AP interface $AP_IFACE not found"
ip link show "$UPLINK_IFACE" >/dev/null 2>&1 || die "Uplink interface $UPLINK_IFACE not found"

# --- Check uplink has internet ---
info "Checking uplink $UPLINK_IFACE has connectivity..."
if ! ping -c 1 -W 2 -I "$UPLINK_IFACE" 8.8.8.8 >/dev/null 2>&1; then
  warn "Uplink $UPLINK_IFACE cannot reach 8.8.8.8 - internet may not work for clients"
fi

# --- Stop services first ---
info "Stopping hostapd and dnsmasq if running..."
systemctl stop hostapd 2>/dev/null || true
systemctl stop dnsmasq 2>/dev/null || true

# --- Remove AP interface from NetworkManager ---
info "Removing $AP_IFACE from NetworkManager control..."
nmcli dev set "$AP_IFACE" managed no 2>/dev/null || true
# Disconnect any existing connection on the AP interface
nmcli dev disconnect "$AP_IFACE" 2>/dev/null || true

# --- Configure AP interface manually (skip netplan, it's unreliable) ---
info "Configuring $AP_IFACE with IP $AP_ADDR/$CIDR..."
ip addr flush dev "$AP_IFACE" 2>/dev/null || true
ip link set "$AP_IFACE" down 2>/dev/null || true
ip addr add "$AP_ADDR/$CIDR" dev "$AP_IFACE"
ip link set "$AP_IFACE" up

# Verify interface is up with IP
sleep 1
if ! ip addr show "$AP_IFACE" | grep -q "$AP_ADDR"; then
  die "Failed to assign IP $AP_ADDR to $AP_IFACE"
fi
ok "$AP_IFACE is up with IP $AP_ADDR"

# --- Write hostapd config ---
HOSTAPD_CONF="/etc/hostapd/hostapd.conf"
info "Writing hostapd config: $HOSTAPD_CONF"
COUNTRY="${COUNTRY:-US}"
cat > "$HOSTAPD_CONF" <<EOF
# Generated by sticky_bandits
interface=$AP_IFACE
driver=nl80211

# Regulatory
country_code=$COUNTRY
ieee80211d=1

# Basic
ssid=$SSID
hw_mode=g
channel=$CHANNEL

# 802.11n support
ieee80211n=1
wmm_enabled=1
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40]

# Security - WPA2-PSK with broad compatibility
auth_algs=1
wpa=2
wpa_passphrase=$PASSPHRASE
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP CCMP
rsn_pairwise=CCMP

# Make sure we're visible
ignore_broadcast_ssid=0
EOF

# Ensure /etc/default/hostapd points to our conf
echo "DAEMON_CONF=\"$HOSTAPD_CONF\"" > /etc/default/hostapd

# --- Start hostapd first (this puts interface in AP mode) ---
info "Starting hostapd..."
systemctl unmask hostapd >/dev/null 2>&1 || true
systemctl start hostapd
sleep 2

# Verify hostapd is running and interface is in AP mode
if ! systemctl is-active --quiet hostapd; then
  systemctl status hostapd --no-pager || true
  die "hostapd failed to start"
fi

if ! iw dev "$AP_IFACE" info 2>/dev/null | grep -q "type AP"; then
  iw dev "$AP_IFACE" info || true
  die "$AP_IFACE is not in AP mode"
fi
ok "hostapd running, $AP_IFACE in AP mode"

# --- Write dnsmasq config ---
DNSMASQ_DROPIN="/etc/dnsmasq.d/sticky-bandits.conf"
info "Writing dnsmasq config: $DNSMASQ_DROPIN"
cat > "$DNSMASQ_DROPIN" <<EOF
# Generated by sticky_bandits
interface=$AP_IFACE
bind-interfaces

# DHCP range
dhcp-range=$DHCP_START,$DHCP_END,$LEASE_TIME
dhcp-option=3,$AP_ADDR
dhcp-option=6,$AP_ADDR

# Logging
log-queries
log-dhcp
EOF

# --- Start dnsmasq ---
info "Starting dnsmasq..."
systemctl start dnsmasq
sleep 1

if ! systemctl is-active --quiet dnsmasq; then
  systemctl status dnsmasq --no-pager || true
  journalctl -u dnsmasq --no-pager -n 20 || true
  die "dnsmasq failed to start"
fi
ok "dnsmasq running"

# --- Enable IP forwarding ---
info "Enabling IPv4 forwarding..."
echo 1 > /proc/sys/net/ipv4/ip_forward
echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-sticky-bandits.conf

# --- Configure iptables NAT ---
info "Configuring iptables NAT..."

# Clean up old rules first
iptables -D FORWARD -j SB_FORWARD 2>/dev/null || true
iptables -F SB_FORWARD 2>/dev/null || true
iptables -X SB_FORWARD 2>/dev/null || true
iptables -t nat -D POSTROUTING -j SB_POSTROUTING 2>/dev/null || true
iptables -t nat -F SB_POSTROUTING 2>/dev/null || true
iptables -t nat -X SB_POSTROUTING 2>/dev/null || true

# Create forwarding chain
iptables -N SB_FORWARD
iptables -I FORWARD 1 -j SB_FORWARD
iptables -A SB_FORWARD -i "$UPLINK_IFACE" -o "$AP_IFACE" -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A SB_FORWARD -i "$AP_IFACE" -o "$UPLINK_IFACE" -j ACCEPT
iptables -A SB_FORWARD -j RETURN

# Create NAT chain
iptables -t nat -N SB_POSTROUTING
iptables -t nat -I POSTROUTING 1 -j SB_POSTROUTING
iptables -t nat -A SB_POSTROUTING -o "$UPLINK_IFACE" -j MASQUERADE
iptables -t nat -A SB_POSTROUTING -j RETURN

ok "iptables configured"

# --- Save state ---
cat > "$STATE_DIR/ap_config" <<EOF
AP_IFACE=$AP_IFACE
UPLINK_IFACE=$UPLINK_IFACE
SSID=$SSID
AP_ADDR=$AP_ADDR
DHCP_START=$DHCP_START
DHCP_END=$DHCP_END
EOF

# --- Final verification ---
echo ""
ok "AP is up!"
echo "    SSID: $SSID"
echo "    Password: $PASSPHRASE"
echo "    Gateway: $AP_ADDR"
echo "    DHCP range: $DHCP_START - $DHCP_END"
echo ""
echo "Verify with:"
echo "    iw dev $AP_IFACE info"
echo "    sudo journalctl -u hostapd -f"
echo "    sudo journalctl -u dnsmasq -f"
echo ""
echo "Start capture with:"
echo "    sudo AP_IFACE=$AP_IFACE bash scripts/capture.sh start"
