#!/usr/bin/env bash
# Phase 2: DNS hijack and intercept server
# 
# This script:
# 1. Ensures AP is up via full_setup.sh
# 2. Adds DNS override to point ws.stickerbox.com to our gateway
# 3. Reloads dnsmasq config (not restart, to avoid breaking things)
# 4. Runs the intercept HTTPS server
# 5. Cleans up DNS overrides when done
#
# Usage: sudo bash scripts/phase2_intercept.sh

set -uo pipefail

die() { echo "[FATAL] $*" >&2; exit 1; }
info() { echo "[*] $*"; }
ok() { echo "[+] $*"; }

[[ "${EUID}" -eq 0 ]] || die "Run with sudo"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INTERCEPT_CONF="/etc/dnsmasq.d/intercept.conf"
GATEWAY_IP="${GATEWAY_IP:-192.168.60.1}"

cleanup() {
    info "Cleaning up DNS override..."
    rm -f "$INTERCEPT_CONF"
    # Send SIGHUP to reload config, don't restart
    killall -HUP dnsmasq 2>/dev/null || true
    ok "DNS override removed"
}

# Set trap to cleanup on exit
trap cleanup EXIT

info "=== Phase 2: DNS Intercept ==="
echo ""

# Step 0: Make sure AP is up
info "Ensuring AP is running..."
if ! systemctl is-active --quiet hostapd; then
    info "AP not running, starting full setup..."
    bash "$REPO_ROOT/scripts/full_setup.sh"
fi

if ! systemctl is-active --quiet hostapd; then
    die "Failed to start AP"
fi

if ! systemctl is-active --quiet dnsmasq; then
    die "dnsmasq not running"
fi

ok "AP is running"
echo ""

# Step 1: Write DNS override
info "Adding DNS override for ws.stickerbox.com -> $GATEWAY_IP"
cat > "$INTERCEPT_CONF" <<EOF
# Generated by phase2_intercept.sh
address=/ws.stickerbox.com/$GATEWAY_IP
EOF

ok "DNS config written"

# Step 2: Reload dnsmasq (SIGHUP reloads config without full restart)
info "Reloading dnsmasq config..."
killall -HUP dnsmasq 2>/dev/null || systemctl reload dnsmasq 2>/dev/null || systemctl restart dnsmasq

sleep 1

if ! systemctl is-active --quiet dnsmasq; then
    systemctl status dnsmasq --no-pager || true
    die "dnsmasq died after reload"
fi
ok "dnsmasq reloaded"

# Step 3: Verify DNS override works
info "Testing DNS override..."
RESOLVED=$(dig +short ws.stickerbox.com @$GATEWAY_IP 2>/dev/null | head -1 || true)
if [[ "$RESOLVED" == "$GATEWAY_IP" ]]; then
    ok "DNS override working: ws.stickerbox.com -> $GATEWAY_IP"
else
    info "DNS test result: $RESOLVED (may need device to reconnect)"
fi
echo ""

# Step 4: Delete old certs so we regenerate fresh ones
rm -rf "$REPO_ROOT/certs"

# Step 5: Run intercept server
echo "========================================"
echo "INTERCEPT SERVER STARTING"
echo "========================================"
echo ""
echo "Target: ws.stickerbox.com -> $GATEWAY_IP"
echo ""
echo "Trigger the stickerbox device now."
echo "Watch for connection attempts below."
echo "Press Ctrl+C to stop."
echo ""

# Run the server (this blocks until Ctrl+C)
python3 "$REPO_ROOT/scripts/intercept_server.py" --log-file "$REPO_ROOT/logs/intercept.log"

echo ""
ok "Done. Check logs/intercept.log for details."
