#!/usr/bin/env bash
# Phase 2: DNS hijack and intercept server
# 
# This script:
# 1. Adds DNS overrides to point api.stickerbox.com and ws.stickerbox.com to our gateway
# 2. Restarts dnsmasq
# 3. Runs the intercept HTTPS server
# 4. Cleans up DNS overrides when done
#
# Usage: sudo bash scripts/phase2_intercept.sh

set -euo pipefail

die() { echo "[FATAL] $*" >&2; exit 1; }
info() { echo "[*] $*"; }
ok() { echo "[+] $*"; }

[[ "${EUID}" -eq 0 ]] || die "Run with sudo"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INTERCEPT_CONF="/etc/dnsmasq.d/intercept.conf"
GATEWAY_IP="${GATEWAY_IP:-192.168.60.1}"

# Targets to intercept (just the websocket - that's where image generation happens)
TARGETS="ws.stickerbox.com"

cleanup() {
    info "Cleaning up..."
    rm -f "$INTERCEPT_CONF"
    systemctl restart dnsmasq 2>/dev/null || true
    ok "DNS overrides removed"
}

# Set trap to cleanup on exit
trap cleanup EXIT

info "=== Phase 2: DNS Intercept ==="
info "Gateway IP: $GATEWAY_IP"
info "Targets: $TARGETS"
echo ""

# Step 1: Write DNS overrides
info "Adding DNS overrides..."
cat > "$INTERCEPT_CONF" <<EOF
# Generated by phase2_intercept.sh
# Redirect websocket endpoint to our gateway (api.stickerbox.com passes through)
address=/ws.stickerbox.com/$GATEWAY_IP
EOF

ok "DNS config written to $INTERCEPT_CONF"
cat "$INTERCEPT_CONF"
echo ""

# Step 2: Restart dnsmasq
info "Restarting dnsmasq..."
systemctl restart dnsmasq
sleep 1

if ! systemctl is-active --quiet dnsmasq; then
    systemctl status dnsmasq --no-pager || true
    die "dnsmasq failed to restart"
fi
ok "dnsmasq restarted"

# Step 3: Verify DNS override works
info "Testing DNS override..."
RESOLVED=$(dig +short ws.stickerbox.com @127.0.0.1 2>/dev/null | head -1 || true)
if [[ "$RESOLVED" == "$GATEWAY_IP" ]]; then
    ok "DNS override working: ws.stickerbox.com -> $GATEWAY_IP"
else
    echo "[!] DNS override may not be working. Got: $RESOLVED (expected $GATEWAY_IP)"
fi
echo ""

# Step 4: Run intercept server
info "Starting intercept server..."
echo ""
echo "========================================"
echo "INTERCEPT SERVER RUNNING"
echo "========================================"
echo ""
echo "Now trigger the device. Watch for connection attempts."
echo "Press Ctrl+C to stop and see results."
echo ""

# Run the server (this blocks until Ctrl+C)
python3 "$REPO_ROOT/scripts/intercept_server.py" --log-file "$REPO_ROOT/logs/intercept.log"

# Cleanup happens via trap
echo ""
ok "Done. Check logs/intercept.log for connection details."
